name: nilla-system
favicon: null
layout_spectrum: 0.2862273140344769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: stars
    item: null
    url: null
style: 'https://forresto.github.io/nilla-system/nilla.js'
typography_spectrum: 0.3901483591180295
